services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: task-manager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: task_manager
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
